[package]
name = "guard"
version = "0.1.0"
description = "mCaptcha - a PoW-based CAPTCHA system"
homepage = "https://mcaptcha.org"
repository = "https://github.com/mCaptcha/guard"
documentation = "https://mcaptcha.org/docs/"
lisense = "AGPLv3 or later version"
authors = ["realaravinth <realaravinth@batsense.net>"]
edition = "2018"
default-run = "guard"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "guard"
path = "./src/main.rs"

[[bin]]
name = "tests-migrate"
path = "./src/tests-migrate.rs"

[dependencies]
actix-web = "3"
actix = "0.11"
actix-identity = "0.3"
actix-http = "2.2"
actix-rt = "2"
awc = "3.0.0-beta.3"

futures = "0.3"

sqlx = { version = "0.5.0", features = [ "runtime-actix-rustls", "postgres" ] }
argon2-creds = { version = "0.2", git = "https://github.com/realaravinth/argon2-creds", commit = "61f2d1d" }

config = "0.11"
validator = { version = "0.13", features = ["derive"]}

derive_builder = "0.9"
derive_more = "0.99"

serde = "1"
serde_json = "1"

url = "2.2"

pretty_env_logger = "0.4"
log = "0.4"

lazy_static = "1.4"


m_captcha = { version = "0.1.2", git = "https://github.com/mCaptcha/mCaptcha" }

rand = "0.8"

[dev-dependencies]
rt = { package = "actix-rt", version = "1"}
