[package]
name = "guard"
version = "0.1.0"
authors = ["realaravinth <realaravinth@batsense.net>"]
edition = "2018"
default-run = "guard"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "guard"
path = "./src/main.rs"

[[bin]]
name = "tests-migrate"
path = "./src/tests-migrate.rs"



[dependencies]
actix-web = "3"
actix = "0.10"
actix-identity = "0.3"
actix-http = "2.2"

sqlx = { version = "0.4.0", features = [ "runtime-actix-rustls", "postgres" ] }
argon2-creds = { version = "0.2", git = "https://github.com/realaravinth/argon2-creds", commit = "61f2d1d" }

config = "0.10"
validator = { version = "0.12", features = ["derive"]}

derive_builder = "0.9"
derive_more = "0.99"

serde = "1"
serde_json = "1"

url = "2.2"

pretty_env_logger = "0.4"
log = "0.4"

lazy_static = "1.4"


m_captcha = { version = "0.1.0", git = "https://github.com/mCaptcha/mCaptcha", tag = "0.1.0" }

rand = "0.8"


[dev-dependencies]
actix-rt = "1"
